# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170131_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
