# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.10.5 on 2017-01-29 20:05
=======
# Generated by Django 1.10.5 on 2017-01-29 20:03
>>>>>>> e47f4107b2bebb6e6eebc72f1a943b7d9b28d3db
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wootapp', '0002_auto_20170129_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default='random', max_length=200),
            preserve_default=False,
        ),
    ]
