# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wootapp', '0005_auto_20170130_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to='apps/wootapp/static/images/dbitems/'),
        ),
    ]
