# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wootapp', '0008_auto_20170130_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cc',
            name='user',
        ),
        migrations.AddField(
            model_name='purchased',
            name='charge_id',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='purchased',
            name='status',
            field=models.CharField(default='open', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchased',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='CC',
        ),
    ]
