# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wootapp', '0009_auto_20170130_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchased',
            new_name='Purchases',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='item',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
