# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wootapp', '0010_auto_20170131_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.Users'),
        ),
    ]
